  PROGRAMA teste;
 VarIAVEIS
  A  :ARRAnjO[12..14] DE INTEIRO;
   TECLA:CARAcTER;
   RR   :CARACTER;
   i    :INtEIRO;
   D    :INTEIRO;
    B    :INTEIRO;
  INICIO
        INICIO
           I:=(1+2)-(4+5)*-5+5;
          PARA I:=I ATE I FACA
           INICIO
              B:=B+I;
            FIM;
         EScrEVA(i,'KSDJK45454',I,'JKJK');
         ESCREVA('TODO INDO BEM');
         LEIA(B);
        FIM;
       ENQUANTO ((I=1)E(I<4))OU(I=4) FACA
              INICIO
          ESCREVA('LEO O BOM');
          ESCREVA('  ');
       FIM;
         SE I=1 ENTAO
     SE B > I ENTAO
           INICIO
         ESCREVA('VA PARA O INFERNO ');
       FIM;
       SENAO
       ESCREVA('VAS TU');
    REPITA;
        i:=1+I;
      ATE (I<B);
   FIM.
